name: Build Project

on:
  push:
    branches:
      - main # Or 'master', depending on your default branch
  workflow_dispatch: # Allows manual triggering from the Actions tab

# Minimal permissions needed for checkout and artifact upload
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use a current LTS version

      - name: Install dependencies
        run: npm ci # Use 'ci' for cleaner installs in CI

      - name: Build project
        run: npm run build # Runs 'vite build'

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output # Name of the artifact zip file
          path: ./dist # Path to the directory to upload
          retention-days: 7 # Optional: How long to keep the artifact (default is 90)